### ISSUE TITLE
Can it be vertical and horizontal?

### ISSUE THREAD

**Issue by staugur** [silvio-r/spop#3]
Hope to answer, thank you!

**Comment by silvio-r** [comment]
Hi @staugur, what do you mean with vertical?
If it's the shape of the spop, it's just horizontal ... why do you need vertical?

**Comment by staugur** [comment]
I'm sorry, my English is not very good. I mean it is in the vertical and horizontal direction of the screen, in the center, like the lower picture:
![](https://open.saintic.com/static/img/upload/201802091013571919.png)

**Comment by silvio-r** [comment]
No, spop don't have that option. Maybe in a future release...
