### ISSUE TITLE
explain Options > ”funtion()“ spelling mistake

### ISSUE THREAD

**Issue by NickHi** [silvio-r/spop#4]
explain Options > ”funtion()“ spelling mistake    "function()"

**Comment by NickHi** [comment]
spop({
	template  : null,// string required. Without it nothing happens!
	style     : 'info',// success, warning or error
	autoclose : false,// miliseconds
	position  : 'top-right',// top-left top-center bottom-left bottom-center bottom-right
	icon      : true,// or false
	group     : false,// string, add a id reference
	onOpen    : **function**() { },
	onClose   : **function**() { }
});

**Minor error**

**Comment by silvio-r** [comment]
Thank you @NickHi
